#!/bin/sh

### BEGIN INIT INFO
# Provides:             garage
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    Garage door controller
### END INIT INFO

cd /home/pi/garage

(/bin/sleep 30s; /usr/bin/sudo /usr/bin/nohup /usr/bin/python controller.py) &
